export const BASKET_ADD_ITEM = 'BASKE_ADD_ITEM';
export const BASKET_REMOVE_ITEM = 'BASKE_REMOVE_ITEM';
export const BASKET_SHIPPING_SAVE = 'BASKE_SHIPPING_SAVE';
export const BASKET_PAYMENT_SAVE = 'BASKE_PAYMENT_SAVE';