export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAIL = 'PRODUCT_FAIL';

export const PRODUCT_REQUEST_DET = 'PRODUCT_REQUEST_DET';
export const PRODUCT_SUCCESS_DET = 'PRODUCT_SUCCESS_DET';
export const PRODUCT_FAIL_DET = 'PRODUCT_FAIL_DET';