export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAIL = 'PRODUCT_FAIL';

export const PRODUCT_REQUEST_DET = 'PRODUCT_REQUEST_DET';
export const PRODUCT_SUCCESS_DET = 'PRODUCT_SUCCESS_DET';
export const PRODUCT_FAIL_DET = 'PRODUCT_FAIL_DET';

export const PRODUCT_SAVE_REQUEST = 'PRODUCT_SAVE_REQUEST';
export const PRODUCT_SAVE_SUCCESS = 'PRODUCT_SAVE_SUCCESS';
export const PRODUCT_SAVE_FAIL = 'PRODUCT_SAVE_FAIL';

